# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.eva.root] run return 0
execute on passengers if entity @s[tag=aj.eva.data] unless data entity @s {data:{rigHash: '8bbe2ed7406dced26348bee2e552b4bd528f448e6248498e06b9a418daeea496'}} on vehicle run function animated_java:eva/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1