# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.eva.root] run return 0
execute on passengers if entity @s[tag=aj.eva.data] unless data entity @s {data:{rigHash: 'ab525926b13313ffed26c9bd8e0f454980718d82ea636266b093c067e38d0c2a'}} on vehicle run function animated_java:eva/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1