# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.eva.root] run return 0
execute on passengers if entity @s[tag=aj.eva.data] unless data entity @s {data:{rigHash: 'f97bc385b5b6c8b95093d3f936a203b00d01ad3befca98868889fc71b6983362'}} on vehicle run function animated_java:eva/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1