# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.eva.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'eva', 'function_path': 'animated_java:eva/animations/fall/stop'}
tag @s remove aj.eva.animation.fall.playing
scoreboard players set @s aj.fall.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:eva/animations/fall/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only