# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
summon minecraft:item_display ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.eva.locator', 'aj.eva.locator.interior']}
execute as @e[type=minecraft:item_display,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:eva/zzz/2
data modify entity @s data.locators.interior.uuid set from storage aj:uuid main.out
summon minecraft:item_display ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.eva.locator', 'aj.eva.locator.chair']}
execute as @e[type=minecraft:item_display,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:eva/zzz/3
data modify entity @s data.locators.chair.uuid set from storage aj:uuid main.out
summon minecraft:interaction ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.eva.locator', 'aj.eva.locator.clicker']}
execute as @e[type=minecraft:interaction,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:eva/zzz/4
data modify entity @s data.locators.clicker.uuid set from storage aj:uuid main.out
summon minecraft:item_display ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.eva.locator', 'aj.eva.locator.right_foot']}
execute as @e[type=minecraft:item_display,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:eva/zzz/5
data modify entity @s data.locators.right_foot.uuid set from storage aj:uuid main.out
summon minecraft:item_display ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.eva.locator', 'aj.eva.locator.left_foot']}
execute as @e[type=minecraft:item_display,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:eva/zzz/6
data modify entity @s data.locators.left_foot.uuid set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.eva.bone.door] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_door set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.eva.bone.entry_plug] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_entry_plug set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.eva.bone.jaw] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_jaw set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.eva.bone.head] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.eva.bone.offhand] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_offhand set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.eva.bone.left_forearm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_forearm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.eva.bone.left_arm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_arm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.eva.bone.mainhand] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_mainhand set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.eva.bone.right_forearm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_forearm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.eva.bone.right_arm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_arm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.eva.bone.wing] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_wing set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.eva.bone.top_op] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_top_op set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.eva.bone.bottom_op] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bottom_op set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.eva.bone.chest] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_chest set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.eva.bone.right_foot] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_foot set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.eva.bone.right_calf] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_calf set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.eva.bone.right_leg] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_leg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.eva.bone.left_foot] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_foot set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.eva.bone.left_calf] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_calf set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.eva.bone.left_leg] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_leg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.eva.bone.torso] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_torso set from storage aj:uuid main.out