# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:temp uuid set from entity @s data.locators.interior.uuid
function animated_java:eva/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.chair.uuid
function animated_java:eva/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.clicker.uuid
function animated_java:eva/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.right_foot.uuid
function animated_java:eva/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.left_foot.uuid
function animated_java:eva/zzz/execute with storage aj:temp