# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.new
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s item set value {id:"minecraft:name_tag",count:1,components:{"minecraft:custom_model_data":2}}
data modify entity @s item_display set value "head"
data modify entity @s transformation.translation set value [0.0f,8.9f,-0.2f]
data modify entity @s teleport_duration set value 3