# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:eva/root/zzz/2 with entity @s data.locators.interior
function animated_java:eva/root/zzz/4 with entity @s data.locators.chair
function animated_java:eva/root/zzz/6 with entity @s data.locators.clicker