# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
summon minecraft:armor_stand ~ ~ ~ {Tags:['aj.new', 'aj.global.locator', 'aj.eva.locator', 'aj.eva.locator']}
execute as @e[type=minecraft:armor_stand,tag=aj.new,tag=aj.global.locator,limit=1,distance=..0.01] run function animated_java:eva/zzz/2
data modify entity @s data.locators.floor.uuid set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.eva.node.door] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_door set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.eva.node.entry_plug] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_entry_plug set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.eva.node.jaw] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_jaw set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.eva.node.head] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.eva.node.offhand] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_offhand set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.eva.node.left_forearm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_forearm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.eva.node.left_arm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_arm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.eva.node.mainhand] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_mainhand set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.eva.node.right_forearm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_forearm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.eva.node.right_arm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_arm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.eva.node.wing] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_wing set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.eva.node.top_op] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_top_op set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.eva.node.bottom_op] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bottom_op set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.eva.node.chest] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_chest set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.eva.node.right_foot] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_foot set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.eva.node.right_calf] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_calf set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.eva.node.right_leg] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_leg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.eva.node.left_foot] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_foot set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.eva.node.left_calf] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_calf set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.eva.node.left_leg] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_leg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.eva.node.torso] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_torso set from storage aj:uuid main.out